[package]
name = "xmas-bundler"
version = "0.1.0"
edition = "2021"

[dependencies]
rolldown = { git = "https://github.com/rolldown/rolldown", package = "rolldown", tag = "v1.0.0-beta.57", features = [
    "experimental",
] }
clap = { version = "4.5.4", features = ["derive"] }
thiserror = "2.0.17"
